config/routes.rb
Fogatta::Application.routes.draw do

  resources :messages
  root to: "messages#index"

  match "/auth/authentication" => "sessions#authentication", as: :github_auth
  match "/signout" => "sessions#destroy", as: :signout
end

app/models/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Timestamps
  field :author
  field :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :require_login
  protect_from_forgery
  helper_method :current_user

  protected

  def current_user
    session[:user]
  end

  def require_login
    render :template => "session/info" unless current_user
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def create
    @message = Message.create!(params[:message].merge({author: current_user[:info][:nickname]}))
    PrivatePub.publish_to("/messages/new", message: @message)
  end
end

app/controllers/sessions_controller.rb
require "uri"
require "net/http"

class SessionsController < ApplicationController
  skip_before_filter :require_login

  def authentication

    # Load data from GitHub
    auth = GitHub.get_auth(params[:code])
    if auth.blank?
      redirect_to root_url, :notice => "We're sorry, but there are some problems with the authentication."
      return
    end

    # Load repositories
    repo_names = GitHub::User.new(auth).repo_names
    if not repo_names.include?(GITHUB_REPOSITORY)
      redirect_to root_url, :notice => "We're sorry, but you can't access."
      return
    end

    session[:user] = {
      uid: auth[:user]['id'],
      token: auth[:token],
      info: {
        image: auth[:user]['avatar_url'],
        nickname: auth[:user]['login']
      }
    }

    redirect_to root_url, :notice => "Welcome #{auth[:user]['login']}!"
  end

  def destroy
    session[:user] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fogatta</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/index.html.haml
%h1 Chat

%ul#chat
  - @messages.each do |message|
    %li
      %strong.autor= "[#{message.created_at if message.created_at}] #{message.author}:"
      %span= message.content

= form_for Message.new, remote: true do |f|
  = f.text_field :content
  = f.submit "Send"

= subscribe_to "/messages/new"

app/views/session/info.html.haml
%div.row
  %div.span6.offset3
    .auth-required
      %h2 Sign in

      %h4
        In order to ensure that you have access to the repository, you have to
        = link_to "sign in with your GitHub account.", GitHub.url_for_auth(github_auth_url)